# Generated by Django 4.1 on 2023-07-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
