# Generated by Django 4.1 on 2023-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_pet_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, max_length=512, upload_to='fotos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
