# Generated by Django 4.1 on 2023-07-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_pet_foto_alter_pet_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.PositiveIntegerField(),
        ),
    ]
