# Generated by Django 4.1 on 2023-07-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0009_alter_pet_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='foto',
            field=models.ImageField(blank=True, max_length=312, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
